server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/octen_java_exam_db
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: secretkey1234567890
  expiration: 3600000

currency:
  api: https://api.privatbank.ua/p24api/pubinfo?json&exchange&coursid=5
